Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project_parcial/', include('project_parcial.urls'))
]

Proyecto/project_parcial/urls.py
from . import views
from django.urls import path

app_name = 'project_parcial'

urlpatterns =[
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('register_user',views.register_user,name='register_user'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('view_tareas',views.view_tareas,name='view_tareas'),
]

Proyecto/project_parcial/models.py
from django.db import models

# Create your models here.
class usuario(models.Model):
    nombre = models.CharField(max_length=64,default='')
    apellido = models.CharField(max_length=64,default='')
    codigo_usuario = models.CharField(max_length=64,default='')
    clave = models.CharField(max_length=64,default='')

class tarea(models.Model):
    titulo = models.CharField(max_length=64,default='')
    descripcion = models.CharField(max_length=64,default='')
    f_creacion = models.CharField(max_length=64,default='')
    f_entrega = models.CharField(max_length=64,default='')
    usuario_designado = models.CharField(max_length=64,default='')

Proyecto/project_parcial/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import usuario
from .models import tarea 

# Create your views here.
lista_usuarios = [['Fabio','Torres','20'],['Cristiano','Ronaldo','37'],['Lionel','Messi','35']]

def index(request):
    return HttpResponse('Esta es mi primera vista')

def login(request):
    if request.method == 'POST':
        usuario_solicitante = []
        nombre = request.POST.get('nombreUsuario')
        clave = request.POST.get('clave')
        usuario_solicitante.append(str(nombre))
        usuario_solicitante.append(str(clave))
        usuario(nombre=str(nombre),clave=str(clave)).save()
    return render(request,'project_parcial/login.html',{
        'usuarios': usuario.objects.all(),
    })
def dashboard(request):
    return render(request,'project_parcial/dashboard.html')
def view_tareas(request):
    return  render(request,'project_parcial/view_tareas.html')
def register_user(request):
    if request.method == 'POST':
        nuevoUsuario = []
        nombre = request.POST.get('nombreUsuario')
        apellido = request.POST.get('apellidoUsuario')
        codigo_usuario = request.POST.get('codigo_usuario')
        clave = request.POST.get('clave')
        nuevoUsuario.append(str(nombre))
        nuevoUsuario.append(str(apellido))
        nuevoUsuario.append(str(codigo_usuario))
        nuevoUsuario.append(str(clave))
        usuario(nombre=str(nombre),apellido=str(apellido),codigo_usuario=str(codigo_usuario),clave=str(clave)).save()
    return render(request,'project_parcial/register_user.html',{
        'usuarios': usuario.objects.all(),
    })

Proyecto/project_parcial/templates/project_parcial/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard</title>
        <link href="login.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css" integrity="sha512-gMjQeDaELJ0ryCI+FtItusU9MkAifCZcGq789FrzkiM49D8lbDhoaUaIX4ASU187wofMNlgBJ4ckbrXM9sE6Pg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    </head>
    <body style="background-color:#33B5FF">
        <div class="row headerSide justify-content-end" style="color:white; background-color: #3386FF;">
            <div class="col-12">
                <div class="row h-100">
                    <h2>Dashboard</h2>
                </div>
            </div>
        </div>
        

        <div class="row headerSide justify-content-end" style="color:white;">
            <div class="col-12">
                <div class="row h-100 align-items-center">
                    
                    <form method = "post" url="{% url 'project_parcial:dashboard' %}">
                    {% csrf_token %}
                        <div>
                            <h4>Task</h4>
                            <h4>Task owner</h4>
                            <h4>Status</h4>
                        </div>                        
                    </form>                    
                </div>
            </div>
        </div>
        <div class="row headerSide justify-content-end" style="color:white; background-color: #3386FF;">
            <div class="col-12">
                <div class="row h-100">
                    <h2>Task Period</h2>
                </div>
            </div>
        </div>
        
        <div class="row headerSide justify-content-end" style="color:white;">
            <div class="col-12">
                <div class="row h-100 align-items-center">
                    
                    <form method = "post" url="{% url 'project_parcial:login' %}">
                    {% csrf_token %}
                        <div>
                            <h4>Task</h4>
                            <h4>Task owner</h4>
                            <h4>Status</h4>
                        </div>                        
                    </form>                    
                </div>
            </div>
        </div>
        
    </body>
</html>

Proyecto/project_parcial/templates/project_parcial/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h2>Bienvenido a este proyecto</h2>
        <h4>Usuarios del proyecto</h4>
        <br>
        {% for usuario in usuarios %}
        <h4>Nombre: {{ usuario.nombre }}</h4>
        <h4>Apellido: {{ usuario.apellido }}</h4>
        <h4>Codigo: {{ usuario.codigo_usuario }}</h4>
        <h4>Clave: {{ usuario.clave }}</h4>
        <br>
        {% endfor %}
        <br>
        <h4>Ingrese un nuevo usuario</h4>
        <form method = "post" url="{% url 'project_parcial:login' %}">
        {% csrf_token %}
            <div>
                <h4>Ingrese el nombre</h4>
                <input type="text" name="nombreUsuario">
            </div>
            <div>
                <h4>Ingrese el apellido</h4>
                <input type="text" name="apellidoUsuario">
            </div>
            <div>
                <h4>Ingrese el codigo</h4>
                <input type="number" name="codigo_usuario">
            </div>
            <div>
                <h4>Ingrese la clave</h4>
                <input type="number" name="clave">
            </div>
            <br>
            <button type="submit">Registrar usuario</button>
        </form>
    </body>
</html>

Proyecto/project_parcial/templates/project_parcial/register_user.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <link href="register_user.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css" integrity="sha512-gMjQeDaELJ0ryCI+FtItusU9MkAifCZcGq789FrzkiM49D8lbDhoaUaIX4ASU187wofMNlgBJ4ckbrXM9sE6Pg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    </head>
    <body  style="background-color: #33B5FF;">
        <div class="row headerSide justify-content-end" style="color:white; background-color:#3386FF;">
            <div class="col-12">
                <div class="row h-100 align-items-center text-center">
                    <h2>Bienvenido a este proyecto</h2>
                    <h4>Registro de nuevo usuario</h4>
                </div>
            </div>
        </div>
        <br>

        <div class="row headerSide justify-content-end" style="color:white;">
            <div class="col-12">
                <div class="row h-100 align-items-center text-center">
                    
                    <form method = "post" url="{% url 'project_parcial:register_user' %}">
                    {% csrf_token %}
                        <div>
                            <h4>Ingrese un nuevo usuario</h4>
                            <h4>Ingrese el nombre</h4>
                            <input type="text" name="nombreUsuario">
                        </div>
                        <div>
                            <h4>Ingrese el apellido</h4>
                            <input type="text" name="apellidoUsuario">
                        </div>
                        <div>
                            <h4>Ingrese el codigo</h4>
                            <input type="number" name="codigo_usuario">
                        </div>
                        <div>
                            <h4>Ingrese la clave</h4>
                            <input type="text" name="clave">
                        </div>
                        <br>
                        <button type="submit">Registrar usuario</button>
                    </form>
                    
                    
                </div>
            </div>
        </div>
        <br>
        
        
        
    </body>
</html>

Proyecto/project_parcial/templates/project_parcial/view_tareas.html
<!DOCTYPE html>
<html>
    <head>
        <title>Status</title>
        <link href="login.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css" integrity="sha512-gMjQeDaELJ0ryCI+FtItusU9MkAifCZcGq789FrzkiM49D8lbDhoaUaIX4ASU187wofMNlgBJ4ckbrXM9sE6Pg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    </head>
    <body style="background-color:#33B5FF">
        <div class="row headerSide justify-content-end" style="color:white; background-color: #3386FF;">
            <div class="col-12">
                <div class="row h-100">
                    <h2>Status</h2>
                </div>
            </div>
        </div>
        

        <div class="row headerSide justify-content-end" style="color:white;">
            <div class="col-12">
                <div class="row h-100 align-items-center">
                    
                    <form method = "post" url="{% url 'project_parcial:login' %}">
                    {% csrf_token %}
                        <div>
                            <h4>Task</h4>
                            <h4>Task owner</h4>
                            <h4>Status</h4>
                        </div>                        
                    </form>                    
                </div>
            </div>
        </div>
        <div class="row headerSide justify-content-end" style="color:white; background-color: #3386FF;">
            <div class="col-12">
                <div class="row h-100">
                    <h2>Task Period</h2>
                </div>
            </div>
        </div>
        
        <div class="row headerSide justify-content-end" style="color:white;">
            <div class="col-12">
                <div class="row h-100 align-items-center">
                    
                    <form method = "post" url="{% url 'project_parcial:login' %}">
                    {% csrf_token %}
                        <div>
                            <h4>Task</h4>
                            <h4>Task owner</h4>
                            <h4>Status</h4>
                        </div>                        
                    </form>                    
                </div>
            </div>
        </div>
        
    </body>
</html>